# Generated by Django 5.2.6 on 2025-09-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vulgar', models.CharField(max_length=200)),
                ('nombre_cientifico', models.CharField(max_length=200, unique=True)),
                ('en_peligro', models.BooleanField(default=False)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especies', to='zoologicos.familia')),
            ],
            options={
                'ordering': ['nombre_cientifico'],
            },
        ),
        migrations.CreateModel(
            name='Zoologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('tamano_m2', models.PositiveIntegerField()),
                ('presupuesto_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('animales', models.ManyToManyField(blank=True, related_name='zoos', to='zoologicos.especie')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
